// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqwdsiwbpykouazcjnuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxd2RzaXdicHlrb3VhemNqbnV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NzgzNDksImV4cCI6MjA2MDQ1NDM0OX0.hNY3S_XUamu7R7G7q2hxe511P1uMdY71o0JtZjva93w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);